### ISSUE TITLE
FigureResampler not working for Boxplot and Histogram

### ISSUE THREAD

**Issue by bwassim** [predict-idlab/plotly-resampler#195]
Hello, 
In the last example here https://github.com/predict-idlab/plotly-resampler/blob/main/examples/basic_example.ipynb

go.Histogram and go.Boxplot does not seem to be affected by the limiting points to display in fig = FigureResampler(base_fig, default_n_shown_samples=1000, verbose=False)
why is that?

**Comment by bwassim** [comment]
Oh I see, thanks for your reply. It works really well otherwise.

**Comment by jvdd** [comment]
Hi @bwassim, I ran into this distinction too. Limiting points works for line traces, but histograms and box plots need aggregation rather than point selection.

In [FlexViz](https://github.com/flex-analytics/flexviz) (the successor of plotly-resampler), these are native scalable traces: histograms are fixed-bin aggregates that re-bin on zoom, and box plots are computed from server-side quantiles. The browser receives only bins or summary statistics, never all raw values.

I would be very happy to help if this use case is still relevant :)
