### ISSUE TITLE
construct_update_data function returns no_update value

### ISSUE THREAD

**Issue by chandlereskeyinsight** [predict-idlab/plotly-resampler#282]
I have added the resampler to a Dash application. 

Locally the callback for trace updater is working well but with the deployed version I continue to get the response: 

"Failed to load response data: No data found for resource with given identifier"

every other time the callback runs, which (I think) is because the construct_update_data function returns that there is no update. 

It seems to happen with every other change to the x axis zoom level. For example, once the graph is loaded with data, I will click the + icon to zoom which makes no change to the traces and I get the "Failed to load response data" Response, then on the second zoom it updates traces and the Response in the network tab for _dash-update-component contains the new x and y values from the resampler. 

Is this a known problem or do I have something implemented wrong? Any advice would be appreciated!

**Comment by jonasvdd** [comment]
Hi @chandlereskeyinsight,

Given that from `plotly-resampler>=0.9.2`, we removed `traceUpdater`, see #281and [release notes](https://github.com/predict-idlab/plotly-resampler/releases), this Issue is somewhat stale.

Please let me know when you found the cause or were able get it working with hte latest verison.

Kind regards,
Jonas
