### ISSUE TITLE
Deprecation warnings from pandas

### ISSUE THREAD

**Issue by prokie** [predict-idlab/plotly-resampler#36]
With pandas 1.4 or later I am getting deprecations warnings from figure_resampler.py
```
pandas.UInt64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
```

**Comment by jvdd** [comment]
We check whether the index datatype is integer on this line: 

https://github.com/predict-idlab/plotly-resampler/blob/1c309d6b9b41fd8ad65c555a3038d728f8f20e69/plotly_resampler/figure_resampler.py#L189


Appearantly both [`pd.Int64Index`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Int64Index.html#pandas.Int64Index) and [`pd.UInt64Index`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.UInt64Index.html#pandas.UInt64Index
) are deprecated since pandas v1.4.0 (and will be removed in pandas v2.0).

https://github.com/pandas-dev/pandas/pull/41153

So, in order to comply with pandas its updated index handling, we should check whether the index is a `pd.NumericIndex` of integer `dtype`.
