### ISSUE TITLE
Is there a simple way to convert a `FigureResampler` figure to a standard plotly Figure?

### ISSUE THREAD

**Issue by Alexander-Serov** [predict-idlab/plotly-resampler#41]
So that the standard plotly Figure includes all the points. My global objective is to save a full-points figure to HTML, and if I just do `write_html` on the `FigureResampler` figure, I only get a reduced-resolution version. It's OK if there is no way, but any thoughts would be appreciated.

I have tried 
```
# given that `fig` is a resampled `FigureResampler` figure

from plotly_resampler import FigureResampler
fig2 = FigureResampler(fig, default_n_shown_samples = 100000)
fig2.write_html('overview.html')

# and

import plotly.graph_objs as go
fig3 = go.Figure(fig)
fig3.write_html('overview.html')
```
but it still saves a rescaled version.

Thanks! :)

**Comment by jvdd** [comment]
Hi @Alexander-Serov,

Thanks for submitting this issue!

The behavior you encountered is indeed a bit unexpected and currently under discussion, see #40. 

In my opinion, to save a figure with all the data points, you could save a standard plotly `go.Figure`. There is no benefit in saving a `FigureResampler` figure (as the adaptive data aggregation through dash is not available in a saved html file).

However, I do think we could throw a warning when you want to save a `FigureResampler` figure. 

Also about your code snippet, why not start with `fig` as a `go.Figure` instead of `FigureResampler` figure?
```py
# fig is a go.Figure

## Visualize it interactively with plotly_resampler
FigureResampler(fig).show_dash()

## Save the original plotly Figure with all its data points
fig.write_htm("...")
```

@jonasvdd any comments on how you would handle this?

**Comment by Alexander-Serov** [comment]
Hey @jvdd,

Thanks for a fast reply. Let me clarify the reason for my original question. We use a Jupyter notebook as our user interface. Our users are not really familiar with python, they just execute the cells updating the paths to files that they are interested in. And then they want to save the figures they plot. The way we do it now is that we return a figure handle to the user that she can then save using `write_html` to share with a colleague. This approach worked well until we tried to simplify some of the figures using `FigureResampler`. Now they receive a figure (FigureResampler) handle, but saving does not really work as expected for them since the HTML images are non-zoomable. Since we cannot ask our users to develop in python, we wanted to make the process transparent for them.  I hope this clarifies the motivation for the question.

But I think your snippet would actually solve the problem, thank you!. We will just return the handle to a `Figure` and use the resampler for plotting it in the notebook. Thanks!
