### ISSUE TITLE
Support for plotly express

### ISSUE THREAD

**Issue by sstripps1** [predict-idlab/plotly-resampler#68]
Hello - I really like this tool! Just wondering if it currently supports plotly express figures (specifically `px.scatter`). If not, is this in the roadmap for the near future?

Thanks!

Sam

**Comment by jvdd** [comment]
Hey @sstripps1,

Can you elaborate some more on how you envision supporting plotly express figures? Perhaps your thoughts are in line with the comments of `Apprehensive_Sun_420` in [this reddit thread](https://www.reddit.com/r/datascience/comments/sviwma/comment/hxiltwv) thread?

At the moment, we already support plotly express figures, as `plotly-resampler` can wrap any plotly Figure. See this code snippet for example;
```py
import numpy as np
import plotly.express as px
from plotly_resampler import FigureResampler

x = np.arange(10_000)
noisy_sin = (3 + np.sin(x / 200) + np.random.randn(len(x)) / 10) * x / 1_000

fig = px.scatter(noisy_sin)
fig = FigureResampler(fig)  # wrap the plotly express figure
fig.show_dash(mode="inline")
```

One (significant) drawback is that we cannot use the `hf_x` and `hf_y` arguments in the plotly express interface. This is quite essential when visualizing very large sequential data (as you will otherwise suffer from the slow construction time from plotly graph_object constructors).

Cheers, @jvdd

**Comment by sstripps1** [comment]
Hey @jvdd, thanks for the quick response! My question was primarily in reference to the ability to use the `hf_x` and `hf_y` arguments (as is the case with `Scattergl`), so thanks for clarifying that.

I hadn't considered the case described by `Apprehensive_Sun_420` but I would be interested in a feature like this as well - as little repetitive code as possible is always ideal :)

**Comment by jonasvdd** [comment]
Should be fixed with #70, and #72, will be released with plotly-resampler 0.7.0 🔥

**Comment by sstripps1** [comment]
This is great, thank you so much @jonasvdd ! 🚀

**Comment by jonasvdd** [comment]
Also major credits to @jvdd ! 🚀
